---
# This playbook deploys all site configs.
- hosts: localhost
  tasks:
    - name: Set distribution variables
      include_vars: "os_{{ ansible_facts['Distribution'] }}.yml"
     
- name: apply base configuration to all nodes
  hosts: localhost
        #  remote_user: root
  roles:
    - base
#- name: Configure webservers
 # hosts: webservers
  #remote_user: root

 # roles:
  #  - webservers
