---
# This playbook deploys all site configs.
#
- hosts: all
  tasks:
    - name: Set distribution variables
      include_vars: "os_{{ ansible_facts['os_family'] }}.yml"

- name: apply base configuration to all nodes
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: pytest
      - name: pytest-testinfra
        #  pre_tasks:
        #- name: Update apt cache
        # apt: update_cache=true

  roles:
    - vim
    - git
    - yamllint
    - geerlingguy.pip
    - geerlingguy.docker
